# -*- coding: utf-8 -*-
"""Insightgenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15etoTQlfjXVFGgRktnHYDMo8nhKGdP5E
"""

!pip install openai pandas matplotlib seaborn --quiet

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openai
from google.colab import files
import zipfile
import os
import glob

print("Upload your ZIP file containing CSV/Excel files...")
uploaded = files.upload()

zip_file = list(uploaded.keys())[0]

extract_path = '/content/data'
with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(" Extracted files:")
print(os.listdir(extract_path))

csv_files = glob.glob(os.path.join(extract_path, "*.csv"))
excel_files = glob.glob(os.path.join(extract_path, "*.xlsx"))

print("\nCSV files found:", csv_files)
print("Excel files found:", excel_files)

if csv_files:
    df = pd.read_csv(csv_files[0])
    print("\nLoaded CSV file:", csv_files[0])
elif excel_files:
    df = pd.read_excel(excel_files[0])
    print("\nLoaded Excel file:", excel_files[0])
else:
    raise Exception("No CSV or Excel files found in the ZIP.")

print("\n📊 Data Preview:")
display(df.head())

print("\n📈 Data Summary:")
summary = df.describe(include='all')
display(summary)

numeric_cols = df.select_dtypes(include='number').columns
if len(numeric_cols) > 0:
    plt.figure(figsize=(6,4))
    sns.histplot(df[numeric_cols[0]], kde=True)
    plt.title(f"Distribution of {numeric_cols[0]}")
    plt.show()
else:
    print("⚠️ No numeric columns found for plotting.")

!pip install openai==0.28.0